#!/bin/bash

./makebib
rm *.aux
rm *.bbl
rm *.blg
rm *.lof
rm *.log
rm *.lot
rm *.toc
pdflatex -draftmode fichera-bfichera-phd-physics-2024-source.tex
mv bibliography.bib fichera-bfichera-phd-physics-2024-source.bib
bibtex fichera-bfichera-phd-physics-2024-source
mv fichera-bfichera-phd-physics-2024-source.bib bibliography.bib
pdflatex -draftmode fichera-bfichera-phd-physics-2024-source.tex
pdflatex fichera-bfichera-phd-physics-2024-source.tex
mv fichera-bfichera-phd-physics-2024-source.pdf fichera-bfichera-phd-physics-2024-thesis.pdf
